export const GET_CLASS_DATA_REQUEST = 'GET_CLASS_DATA_REQUEST';
export const GET_CLASS_DATA_SUCCESS = 'GET_CLASS_DATA_SUCCESS';
export const GET_CLASS_DATA_FAIL = 'GET_CLASS_DATA_FAIL';

export const CLASS_CREATE_REQUEST = 'CLASS_CREATE_REQUEST';
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS';
