export const GET_STUDENT_DATA_REQUEST = 'GET_STUDENT_DATA_REQUEST';
export const GET_STUDENT_DATA_SUCCESS = 'GET_STUDENT_DATA_SUCCESS';
export const GET_STUDENT_DATA_FAIL = 'GET_STUDENT_DATA_FAIL';

export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const SEARCH_STUDENT_SUCCESS = 'SEARCH_STUDENT_SUCCESS';
export const SEARCH_STUDENT_FAIL = 'SEARCH_STUDENT_FAIL';

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST';
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS';
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL';

export const STUDENT_GET_DETAIL_REQUEST = 'STUDENT_GET_DETAIL_REQUEST';
export const STUDENT_GET_DETAIL_SUCCESS = 'STUDENT_GET_DETAIL_SUCCESS';
export const STUDENT_GET_DETAIL_FAIL = 'STUDENT_GET_DETAIL_FAIL';

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL';

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST';
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL';
