export const GET_COURSE_DATA_REQUEST = 'GET_COURSE_DATA_REQUEST';
export const GET_COURSE_DATA_SUCCESS = 'GET_COURSE_DATA_SUCCESS';
export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
